OCR_GROUND_TRUTH_FMT = '{}_ocr.{}'
SEG_GROUND_TRUTH_FMT = '{}_seg.{}'
MODEL_FILE = 'model.pkl'

# COLOR
#   Raw regions
CONTEXT_BACKGROUND_COLOR = (0, 0, 0)
BACKGROUND_COLOR = (50, 50, 50)
BASELINE_COLOR = (0, 0, 255)
IMAGE_COLOR = (255, 0, 0)
DRAWING_COLOR = (255, 0, 100)
GLYPH_COLOR = (125, 0, 200)
TITLE_COLOR = (0, 100, 200)
PARAGRAPH_COLOR = (0, 255, 255)
CAPTION_COLOR = (0, 255, 150)
TEXT_BORDER_COLOR = (255, 140, 0)
FLOATING_WORD_COLOR = (0, 255, 25)
TABLE_WORD_COLOR = (0, 100, 25)
#   Illustration and text colors definition
#   NB: we use the same colors as image and paragraph regions, basically converting all other regions into these two
ILLUSTRATION_COLORS = [IMAGE_COLOR, DRAWING_COLOR, GLYPH_COLOR]
TEXT_COLORS = [TITLE_COLOR, PARAGRAPH_COLOR, CAPTION_COLOR, FLOATING_WORD_COLOR, TABLE_WORD_COLOR]
ILLUSTRATION_COLOR = (255, 0, 0)
TEXT_COLOR = (0, 255, 255)

# LABEL
#   Raw regions
CONTEXT_BACKGROUND_LABEL = 0
IMAGE_LABEL = 1
BACKGROUND_LABEL = 2
TITLE_LABEL = 3
PARAGRAPH_LABEL = 4
BASELINE_LABEL = 5
TEXT_BORDER_LABEL = 6
FLOATING_WORD_LABEL = 7
CAPTION_LABEL = 8
TABLE_WORD_LABEL = 9
DRAWING_LABEL = 10
GLYPH_LABEL = 11
#   Illustration and text labels definition
#   NB: we use the same labels as image and paragraph regions, basically converting all other regions into these two
ILLUSTRATION_LABELS = [IMAGE_LABEL, DRAWING_LABEL, GLYPH_LABEL]
TEXT_LABELS = [TITLE_LABEL, PARAGRAPH_LABEL, CAPTION_LABEL, FLOATING_WORD_LABEL, TABLE_WORD_LABEL]
ILLUSTRATION_LABEL = 1
TEXT_LABEL = 4

# MAPPINGS
COLOR_TO_LABEL_MAPPING = {
    BACKGROUND_COLOR: BACKGROUND_LABEL,
    IMAGE_COLOR: IMAGE_LABEL,
    TITLE_COLOR: TITLE_LABEL,
    PARAGRAPH_COLOR: PARAGRAPH_LABEL,
    BASELINE_COLOR: BASELINE_LABEL,
    TEXT_BORDER_COLOR: TEXT_BORDER_LABEL,
    FLOATING_WORD_COLOR: FLOATING_WORD_LABEL,
    CAPTION_COLOR: CAPTION_LABEL,
    TABLE_WORD_COLOR: TABLE_WORD_LABEL,
    DRAWING_COLOR: DRAWING_LABEL,
    GLYPH_COLOR: GLYPH_LABEL,
}

LABEL_TO_COLOR_MAPPING = {
    BACKGROUND_LABEL: BACKGROUND_COLOR,
    IMAGE_LABEL: IMAGE_COLOR,
    TITLE_LABEL: TITLE_COLOR,
    PARAGRAPH_LABEL: PARAGRAPH_COLOR,
    BASELINE_LABEL: BASELINE_COLOR,
    TEXT_BORDER_LABEL: TEXT_BORDER_COLOR,
    FLOATING_WORD_LABEL: FLOATING_WORD_COLOR,
    CAPTION_LABEL: CAPTION_COLOR,
    TABLE_WORD_LABEL: TABLE_WORD_COLOR,
    DRAWING_LABEL: DRAWING_COLOR,
    GLYPH_LABEL: GLYPH_COLOR,
}
